#!/usr/bin/env python3
"""Generate src/spruce/skin_spec.lua from a reference PyUI theme (default: spruceOS's SPRUCE).

The reference theme's PNG dimensions ARE the layout contract PyUI expects per resolution,
so the on-device renderer reproduces every asset at exactly these sizes.

Usage: utils/generate_skin_spec.py [path/to/Themes/SPRUCE]
"""
import json, os, struct, sys

ref = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/ai/CFW/Spruce/git/spruceOS/Themes/SPRUCE")
out = os.path.join(os.path.dirname(__file__), "..", "src", "spruce", "skin_spec.lua")

def png_size(p):
    with open(p, "rb") as f:
        d = f.read(24)
    if d[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", d[16:24])

def scan(dirpath):
    entries = {}
    for name in sorted(os.listdir(dirpath)):
        p = os.path.join(dirpath, name)
        if os.path.isfile(p) and name.lower().endswith(".png"):
            s = png_size(p)
            if s:
                entries[name[:-4]] = s
    return entries

spec = {"skin": {}, "icons": {}, "icons_sel": {}, "icons_app": {}}
for d in sorted(os.listdir(ref)):
    p = os.path.join(ref, d)
    if not os.path.isdir(p):
        continue
    if d == "skin" or (d.startswith("skin_") and "x" in d[5:]):
        res = "640x480" if d == "skin" else d[5:]
        spec["skin"][res] = scan(p)
    elif d == "icons" or (d.startswith("icons_") and "x" in d[6:]):
        res = "640x480" if d == "icons" else d[6:]
        spec["icons"][res] = scan(p)
        sel = os.path.join(p, "sel"); app = os.path.join(p, "app")
        if os.path.isdir(sel): spec["icons_sel"][res] = scan(sel)
        if os.path.isdir(app): spec["icons_app"][res] = scan(app)

def lua_table(d, indent=1):
    pad = "\t" * indent
    lines = ["{"]
    for k in sorted(d):
        v = d[k]
        key = '["%s"]' % k
        if isinstance(v, dict):
            lines.append("%s%s = %s," % (pad, key, lua_table(v, indent + 1)))
        else:
            lines.append("%s%s = { %d, %d }," % (pad, key, v[0], v[1]))
    lines.append("\t" * (indent - 1) + "}")
    return "\n".join(lines)

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("-- GENERATED by utils/generate_skin_spec.py from %s\n" % os.path.basename(ref))
    f.write("-- Asset name -> { width, height } per resolution. Do not edit by hand.\n")
    f.write("return " + lua_table(spec) + "\n")
print("wrote", os.path.normpath(out))
for k, v in spec.items():
    print(k, {r: len(e) for r, e in v.items()})
